language: node_js
node_js:
- 9.5.0
before_install:
- npm i -g npm@6.0.1
branches:
  only:
  - "/.*/"
jobs:
  include:
  - script:
    - npm run lint
    stage: lint
  - script:
    - npm run test-server &
    - npm run test
    stage: unit tests
  - stage: Build docker (dev)
    if: tag IS blank
    install: true
    env:
    - OWNER=streamr
    - IMAGE_NAME=streamr-web3
    - TAG=dev
    script:
    - docker build -t $OWNER/$IMAGE_NAME:$TAG .
    deploy:
    - provider: script
      script: bash .travis_scripts/deploy_docker.sh staging
env:
  global:
  - secure: WANMUsWPzEsBnlx6vzxv2O3d1ZYdbk5oWUTHhN2QQvvnSpKAZLcII/brnDOV3oOGg6Oo9djqImYnVdN38ORZ4OB/GTVdgODRV8wsC4pM99cjJe5jVKcQcWFXRRsShEXG3S0RdGB0gx3Bn0DZs3OGmwCQsZXKLaZTbWl2SZAHnKNus1cpjEoBdS1u++FnT8gGTevoI3vCvWuMGH3ASsfyxwgGjdhtjQ0spCS/+r+vCm+EcjjZeR8+9XKdF9C92ZfAlbUseXgQtmvGY7waVW9uExGGw/aB1Br1rJIC/MZfsoICqnaqHrG49weiaHkReq1/xej5aXYQzfrFDnZAcIkzY+DN78maY8r3FNOq3864YHvBMDonYywEVaWZVRg4fE4tj+asNPWUOrHOKwSvahrUdl34pH1zrlvm8N9Q63EHPeiqgJdXEtNZkR0d8uutvVTY/g+J1MyY60upXzNVOPEyleetdD2hbDwuONEJXE4dS9NLnzqJZlXY19CNC++2I6EbwaoYom268U9wJR0Lk0o4YBeH20NgtMars94bY5G4XaIAyP4g9TLUgoTaSSb8ge6jCrKWuNyWButxn+tHwX/t2gY+IoQhXNR5jxSEpguwyg2755dUcNNVCGLfek8N8Sg2SUe4jHbIqA8h2n6BKDz5JCVQQhAxOXnakmuRRwIoP7c=
  - secure: ku3wChQsdBIE1KUiGqnGtkDSEl0TNiMMONQc+/T1QSnST7pvMo1cnPoby6hMCH2sg6kDuYp4WMz2UzTan9d9c6UDOls1LEUl5o/68RhEiW0+BZeMYo/9tR6chJI920NobRQ83tItUQvPn6BRZHqZYFoNLMjVneo9WQ65dqGpJLlQIMTwjtMX4oUosAP+CIZu+yyPDjxYGqvfMkDI6l78AHSv66BYcOGI9aFdn/0De+XOXbOcvwLHoqdQKhIQqDCPJILv4kxmWcthnYE7A2nK3LgdAU7+Y3oI1oiR9En48lfxlcYaQWcrZiEa9j/AOdMlYwTCmIPtUWAUfoflTg0nlzhm3hgpVlki+jIxkygc732GD9o0eTPFACjFWQCLMshIDVMKjRBaoCok9GEItfLj0e7g1bstznqgk5/OQHqkgAUUiB7qqAZHCvmcf4P5D67GGb4ZHaW6AR/gFZeBqBQEj26P14kC6+qanhL73b0yNm7hLHn/ZHoD9tWp0BujbyoOCxFkQZmAOmj7OuC46fTmBcf0WQhGcxIlDJ/i0+owBi2MnZukdVUELzRN7Ku48jx34qm3gUL4ryhQTGzYX/ebuyDv1i56Jrd9K1FsliXz6HqSDQo68c2gqh43jnu60iaMQCCcwomlr6KQ4oqTSpAb4E2MxlNj64ErfLb+yRAwJdI=
