language: node_js
node_js:
- 9.5.0
before_install:
- npm i -g npm@6.0.1
branches:
  only:
  - "/.*/"
jobs:
  include:
  - script:
    - npm run lint
    stage: lint
  - script:
    - npm run test-server &
    - npm run test
    stage: unit tests
  - stage: Build docker (dev)
    if: tag IS blank
    install: true
    env:
    - OWNER=streamr
    - IMAGE_NAME=streamr-web3
    - TAG=dev
    script:
    - docker build -t $OWNER/$IMAGE_NAME:$TAG .
    deploy:
    - provider: script
      script: bash .travis_scripts/deploy_docker.sh staging
env:
  global:
  - secure: RefTDx4Hm0I4tenE3gmeei8ML5Zp73CAUj0NZf8rScuXw8QxNiSPHEc/uG3vBKziB2mOnOTGa9+t/kX+6h5Y9GKnn4NYY4V6lE3BASaNArhE26zyaoH7mY/qHUWgT9dKi9WcWMewwLsoBrUJbjZzZoPY+QFVMIramtBi39H9229cJRQxPOyfHGsl4GtlpmTc7gn+0G26zRwWDercBINlm8FOLViGlsYHTamALoygv5ogrXJE7x5hLyQMLRifMNj8ToJbFxfpSgC5aWhiNfk6ONNBnvpfPQBjup68gP2KVWsxqA7luniiYUGz6qDIGFLLMI3zztsTIB8DTUF9Zy1L6NxalGX1LLMOLenFVWOedh5uRy051eov0atVc+eJ3kdw2G629UzCNYze/ZmH7eG+UN3+4tQ7u5XQHdzeR+xO1LkbfuLWLMg/WfG38l+9rCsLlUTjTu8JhsKYHolce1tPUKofqbACmQCMv0V+8GaGnty877NJb5qDJMNnygL0agEVWPU+6Cvq0WaGfFFJDhnjUOzG1anpXdqgCFmuSsYgIOqWY7ghRkM16zwqKhip0EcEXafpOTUGVpuUNh0FuVkvRvJyixav+f8jvMFXMC0Bjg15vtpFT4VoP/uWr2YIgVi5tzhea9gWvzk5S1GfHlVGJgdTPbXL+2dQs0HnDGAhhXs=
  - secure: IBozWcNGTchk0JXM+lwWACOHGC4qYN+vxiHuIUaXo5mlqLyJIqRW9KO6lQnBCdt486LTetNV5cURBAtwLxcmQTeBNUaSoc6iLn18yVRtrloCo9O4eqpDsUPJ9OMkwxELbAiuiXjQoe3TGxJFN31T/Mdg7u9l71+vpIf03ttMT7r9oAJRpZhTkBPibsaKnMeY34QJM49FOjYAnoCvq4ZgYXi8t+31Frk4eZnTKYpayv40avE3AzznT+H6IscbQjBlXAnYYQGQbui1uJSOtqba5jxuyil91RBU9vJjTaNEU6ZyAPfjgsP14PD1StriRNXhy8XEjLqMdPM1uEWAbJuziRDVlYMXH0cJe/mjH1Ym0lWXEJx4FxMXVtm5MFu3tWqNEumYMluMH0B+/E3jKB4XzVkvxu/4SVXXdiObkcFbjbZLA8zLYqhu/SOi+mUUdXnAwrA5BQQ8zOZD4IL0sP23med8J6InKJyESywiHVGmsCEUfcbAnZ/oagt/GbxlNtIz3fTEOTP+z2vzEQdahCtyiQkRWvujH+d+qPmYWZqH+VpPLgCp5ifRAJUi7hNSmAgcK22E+ut2wjxKoDe6u5ShIVXTUYj/0qrHR6THaxdQDnmrQ56hR/4M5a53C8Gf0hn1yzwqbvhnCq18JZNuolyClJOkNLf/kjVNWckIkiIaDKg=
