language: node_js
node_js:
  - "9.5.0"
before_install:
  - "npm i -g npm@6.0.1"
branches:
  only:
    - /.*/
jobs:
  include:
    - script:
        - "npm run lint"
      stage: "lint"
    - script:
        - "npm run test-server &"
        - "npm run test"
      stage: "unit tests"
    - stage: Build docker (dev)
      if: tag IS blank
      install: true
      env:
        - OWNER=streamr
        - IMAGE_NAME=streamr-web3
        - TAG=dev
      script:
        - docker build -t $OWNER/$IMAGE_NAME:$TAG .
      deploy:
        - provider: script
          script: bash .travis_scripts/deploy_docker.sh staging
