language: node_js
node_js:
- 9.5.0
before_install:
- npm i -g npm@6.0.1
branches:
  only:
  - "/.*/"
jobs:
  include:
  - script:
    - npm run lint
    stage: lint
  - script:
    - npm run test-server &
    - npm run test
    stage: unit tests
  - stage: Build docker (dev)
    if: tag IS blank
    install: true
    env:
    - OWNER=streamr
    - IMAGE_NAME=streamr-web3
    - TAG=dev
    script:
    - docker build -t $OWNER/$IMAGE_NAME:$TAG .
    deploy:
    - provider: script
      script: bash .travis_scripts/deploy_docker.sh staging
env:
  global:
  - secure: Unjs5RPfV/KrkcgdxDeVjzJen755WM36eMZJzNptZap+qo/D6dqKH21zlVdDIq7InGQ3q2Pie6s2CiF/VruvIda9Wv4zpjVRXIapA4WhClM+mmKL59bksuXLQGG9I1q0OdT07NQ/iktAnNDculwcSfGA8twfnn15pkQIft1PPnzUccKy9B/xT3S5oU782kOhTzB4jHVcbG8eUE014t7I0aHS3JNzpkHgm63oehYlynER6Wc6+uqbSBaGPCb/ifgvrhQ6tPi64F2ZKCzCSdjwaLG7GQlHS6lc9Lu+4sqYE+rharE9LYkDW35CNqqvuBdEjubDhlzf7/KoQ6Bjw/kP2OeRRahIb79tUyYejaR/uCJxWJrC9lyPlT51PgHB5n6ykn8O8cWPPWOg5e6WfhZ6sDINCU6a6J0Xy63fpjH+QVUfqVwxApE5Ho3I7K8a6kjP5TjbVlF3KnyvLSU8Ir//z6pl5nfmhiWC9KC4g5L5N91BT7OgYVqxc/yWNDk8wPzYRvcY74rWqviddbj7ppAM+/mnmeGuUaTDfV/WaGXtQkIY/uk00AebKtMtVNwzpVdzAHjNA9SDbORFHAbNBzARfbViAYQ/h9QYMs0fXzImMFQXPOUYe73oj49xBzFjLSKzFEy4hdGgOFf4cZlghiB4D/gN+1Hzq8jT8P8GLiAkW7Y=
  - secure: Mvz3Lki8hRgfRFfMdX+q3wDsYWx/nCIYPsBwcJT93E0RHXaAN/haF4I45wV6ZDmgUUV3Eb4v5rEMh4NAbBy66gV31kuDyZR1bp8kwk+IIIPHkEXC5CC83d6CdpOthQsdwxikXCZdNcaIpPlKuo6muVG8V5/Y3mZd5lgT7ACyXMbieGkguPvZ3arzYfKLYLAJdxjx1pkO8tsprwUFMVf2DJFXXmiRIJG/w7PkUQscfl0tp/1DbM5DLyKjVqgIEoJMOcTswB1vJbDqSVTET0RCwRf35aSrWlIMCibZGWvn30CE8lRTUpIIAb9Tj4raSK/CcRouG9lBSgB870m/IhKSBcXFxS6Dvhz/U+w9DyaTAPxOIab3ZVQNElJkRWV4tVG5ETBF9ZuZovgSM8Cf65FzVAfFdsMZa2/8v2QoLS9+b95eDBa+hsv6TLwbDCnnABNhnmj1AsNvhUoDbSUkyfLqaFf/5PPqB6EJ6oDknq7Ep5g3088uH1kSYmJrZGyBwyXYhzWxn5Fb9kxZ1eg1SmsRMdIEhHypHg/6eMDE9rzDOQ99aQkDEcoy42FDLoJy65j0uyNyoArxjURhzn073JaHOVuC51jH/5KFCq3bvurmOs9ejV3h0UXK1y2TjoBi6dxusjh60plb+W3q6Za82qFxmeoDrLj3tez48UsxOQVdCLc=
