language: node_js
node_js:
- 9.5.0
before_install:
- npm i -g npm@6.0.1
branches:
  only:
  - "/.*/"
jobs:
  include:
  - script:
    - npm run lint
    stage: lint
  - script:
    - npm run test-server &
    - npm run test
    stage: unit tests
  - stage: Build docker (dev)
    if: tag IS blank
    install: true
    env:
    - OWNER=streamr
    - IMAGE_NAME=streamr-web3
    - TAG=dev
    script:
    - docker build -t $OWNER/$IMAGE_NAME:$TAG .
    deploy:
    - provider: script
      script: bash .travis_scripts/deploy_docker.sh staging
env:
  global:
  - secure: J4brHL4r+WgoRWecW0Zo4+Se3xb+CyGfaUejr7nQYnuUN8j2ZtIiCl3ubO9p4u1+j8DpqUfH1762ukD+uF7Wi5GhwikYloS3zNRdv54nz347yGxkLm+bTFxJvBakVfg+B3+TXvDfOP8xwwsFtpEwyIbIErdl1XVt4EsrRFYVCC52g5s03XL9nJ20UH20oFCdUmc0gH7tcwqD7wBgnMpFxuP+t3v9KC+bdYKk9qB/E1v8EmyKtxfr5cfvn0VjBvgSEfooKsdAnrQT/8JZ9bJNjzROc80TaCyHbuyrzr/gfe7vaoVJjhcHHRWG4AvUFb2a78oGz1dQ6lCG+eEj+/6jRqw9eKjOpZI7vMkj4pgC94Knk+dhu3q4wEz6EhSLv7rOMWfTCOlvKqzzmEj837JUG9JiAknJ9IJAcB98nbr3TFzkkqz05d9GFwIMp49U/LDXHJ31N8FYJ9T2Md0JzWYlUSz82cTjSGplAdzdxgOiuWjhS4aUHbEGiRKleWYAQpvkejJiqMbCt32UVc17xruPa58XeTw955XYRn1ZZCUgGRldzkubEGEqxQMvd9xKQUVtqnjL19uudCeHTPJdz/RGMCNKhWBOnrjVGNcAdNv+B6PubeDvpBzjkOHk910On/JoSGxi7LZ6OB6+Qa7yQwyYQdQMB2jaUTA+QJfnHkUuBOE=
  - secure: cpb+z8sJNmwJ7gJk9x1DoC/dVC0zQT+//2L5NySEulBsmyMuWH3oUic7Re6LsoRJEKNeR7pbAZp55MEkCo4bbw+j9E4l69X1Pzc9rSuV1fNUFemI/WLtqJThnwk7GAzdxEXy6p4Oak8aRlzg6Hm3g61L2Z+Mo1NuGBnTGsSuLPqjdsvzsTCf2e0GHsmbOcPKw6qjq+N7TDUDEHoi3KrmgwZHtG8LEoeGqXp7gGyBsryThO4mUUPK8lyiLAwiMlKZt/MQtk/khsqpkdSvnri7wDQVNopE6m+FZ+XNMJDAVhFeH98DKRgI7jUl5283y0eesYpvGYI2PEUzaAUWp0cCdeSl1mUI4srGYZAU2X75zohC86RWPhBLURKGnZe9qQ7rE4Prtv9oJs39YvcDnOHt3l48u0d017Y3dKlCV9OYnNnQvr/Lxg2U6JedkkLkJsEH2+xUm/02HrZAC235iwrTD1YDmrSbk4UAKv2yZA+61+au0iye0tc6T73jj5dv88PsyBi6xOUkUOtasywzXE/IMYZM+jAm1HY+GKBanUjbHL6ADxIogdJGi9X4mmxiNQkBXV8IbVnu5JGVcBbf1cpXQYTSQf70jlTTZzOtOwUE8SiAHtRFi1IFwqEFfcpYsrp9nSV6kG8Ah4688t8oPaFLgs1M9moVGgFDPNt0DGcsnb8=
