language: node_js
node_js:
- 9.5.0
before_install:
- npm i -g npm@6.0.1
branches:
  only:
  - "/.*/"
jobs:
  include:
  - script:
    - npm run lint
    stage: lint
  - script:
    - npm run test-server &
    - npm run test
    stage: unit tests
  - stage: Build docker (dev)
    if: tag IS blank
    install: true
    env:
    - OWNER=streamr
    - IMAGE_NAME=streamr-web3
    - TAG=dev
    script:
    - docker build -t $OWNER/$IMAGE_NAME:$TAG .
    deploy:
    - provider: script
      script: bash .travis_scripts/deploy_docker.sh staging
env:
  global:
  - secure: Ao5193FDTrSQaUuVzq23rTcc4xsOB+YI00w/dfJ2bhBjUbQSaTZXI/SDeNDCnig7ceiIBskb6v5Uupd39rfmOnCeZYMZ61U4nH2tbVYBoe1Vtd0XUd/HU1VUC9i72z0jFS6HOwQJkA50xb5UxitUZNET0HjvI1iodTrGBisxHyASr/XhXORhmN9mFu3l0ShKnMup6TUnXWYjcc9yiuzAHR6xP6b7dP/42r8npjKiJXk1kb2sJoqV7v+RzJiOEftBGPgCUGLs5/Y1stFnQyh2jXRQ1lr1ZT/XLOFkv2RQ8bPuUkrnzS+xEbm1+bdQBnaq1V4mpmkXZHSVgFV9OtEpppSzu3TuFHRUQ/sk5NTwTap+BxvpdtRt53Nb5FBOjTd/VMn6LsSViC9CrkhWkJJNSv45USQrIECJr/y35Go+WcrqIMw9upB1+5ahBTfQWeaqqAnwRHyehNJuTuowymBcUtmTdBmMWXW4W/44CoPxlHdS8LPd3X+0oYwi3xvZT4jjTvZ4AoZRDMQr6cm5d/yucVjP/ejmS4lTn6l3+wwfzXGw/2ZFNaT0EGUaej6XQpV1zP480pv6PYHlsNbpB2gwIXz+hk/JPXmDi0umGvPDKLdISBDgqPJ6f5b3jJCoy7DXE5jsgp0qRoPHTrldFWB186NcKkEZU6UYOqNLrEl6kbI=
  - secure: rFYiL9gsxg0uQcBQE6qmQLMo9vGw+tkX8FCpjRiRZPqOcw0E9KmiahPPAs3B4rW3CxJMMWPCOTqujfgbQkeyUPb4YgCEth4D/zIaf0naQTvkf1sWOb7pl5wrHLRIWHb/YOUrR73U3Jc2gWZj0TUgE0WyhfTVYPRALlImS5Rj0tjdFwd7kIOKF1XG6h7/6AKi8HJ5UlIXZtEa40LnokCNrOQDTRd7HTD5CXJvNRKj7UtPy7LBzD16oTLOmUj0v8e9iyFkNcOum7iwMDSrTTD3wIQ3HWfz+L4XI3GiC/HljT4FWDkVL8RpKm+cP7xuut+Ut7mWgk0kpoO6Heic89uYoV2bPGruCxPqGnD9SSZ45VkFBq/p4MxaIayX0RHykMVwpKgN3qkvca4ZYX78bEY1l6W5cyCQAVIiGh0gJCHD0HiEHcI3pDzQajXpQGVRj0nMFruhtPCGjXeDj/ZUYPYaWk5984KS88G1K5im+IoSp5klexfoPa11pJjewT5nA4zRKjj+jr/mpqK5e4vF2HHO6fM7o5Yc+m7zAnyjrfSayFHt2CawDB5rY46LxVcZsZy30z0n4E5oTWap9LoDwXPC0cFTfajVq55We/ISjxheBc5tDkUehEiwPFZMf6jUTxQRviIoYsDb8FHLGBTApp9mhPYTT0D96QJWa9VNzs/m5X4=
